"""create files and calculations

Revision ID: b9532b01df0f
Revises: 
Create Date: 2026-07-27 15:21:51.488066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9532b01df0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('digit_0_count', sa.Integer(), nullable=False),
    sa.Column('digit_1_count', sa.Integer(), nullable=False),
    sa.Column('digit_2_count', sa.Integer(), nullable=False),
    sa.Column('digit_3_count', sa.Integer(), nullable=False),
    sa.Column('digit_4_count', sa.Integer(), nullable=False),
    sa.Column('digit_5_count', sa.Integer(), nullable=False),
    sa.Column('digit_6_count', sa.Integer(), nullable=False),
    sa.Column('digit_7_count', sa.Integer(), nullable=False),
    sa.Column('digit_8_count', sa.Integer(), nullable=False),
    sa.Column('digit_9_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_calculations_file_id_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculations')),
    sa.UniqueConstraint('file_id', name=op.f('uq_calculations_file_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculations')
    op.drop_table('files')
    # ### end Alembic commands ###
